### ISSUE TITLE
Mod causing issues with deaths?

### ISSUE THREAD

**Issue by WickedSchnitzel** [Mad-Gnome/vintage_story_leaderboard#1]
First: [Warning] [leaderboards] Dependency 'game': Failed parsing version string '1.19.*' at index 5: Expected PATCH version number, found '*' (best guess: 1.19.0)

Second: I got reports from players that people dying from anything not mob-related (falling damage, spikes etc.) do not die (leaderboards also does not register falling deaths), but instead they do respawn right away with their inventories intact. We are using the "Playercorpse" mod, so i dont know if thats some sort of compatibility problem maybe.

The thing is, that people said that bug appeared with the addition of leaderboards to our server.

**Comment by Mad-Gnome** [comment]
The first line is because the mod is built for version "game": "1.19.*", not sure if there is a better way to build that honestly.

I got the leaderboard deaths working for falling damage and drowning in SP at least.  Followed the same format for starving but didn't wait around to starve to death.

I have had some issues with the inventory thing on my MP server, but we had the leaderboards on before that happened.  But it might have been from a new patch.  I'm losing my inventory when dying in SP from falling now.
